version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 3.3.0
  - dependency-name: gatsby
    versions:
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.3.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 4.0.0
  - dependency-name: gatsby-remark-images
    versions:
    - 5.0.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 5.0.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: algoliasearch
    versions:
    - 4.9.0
  - dependency-name: netlify-cms-app
    versions:
    - 2.14.35
    - 2.14.37
    - 2.14.38
    - 2.14.40
    - 2.14.43
    - 2.14.45
  - dependency-name: gatsby-plugin-netlify-cms
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: gsap
    versions:
    - 3.6.1
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
